version: "3.8"

services:
  django-app:
    build:
      context: .
    image: django-app
    container_name: django-app
    ports:
      - "8000:8000"
    networks:
      - django-app-net

networks:
  django-app-net:
